### ISSUE TITLE
rcmdcheck fail

### ISSUE THREAD

**Issue by kadyb** [yihui/testit#11]
Hi! I tried to run tests in `rcmdcheck` but with [no success](https://github.com/kadyb/rgugik/runs/1156707967?check_suite_focus=true). 

Log:
```r
* checking tests ...
  Running ‘test-all.R’
 ERROR
Running the tests in ‘tests/test-all.R’ failed.
Complete output:
  > library(testit)
  > test_pkg('rgugik')
  Linking to GEOS 3.8.1, GDAL 3.1.1, PROJ 6.3.1
  Error from parse_and_simplify(txt = txt, simplifyVector = simplifyVector,  ... 
  Error in parse_con(txt, bigint_as_char) : 
    lexical error: invalid char in json text.
                                         <html><head><title>Request Reje
                       (right here) ------^
  Calls: test_pkg ... <Anonymous> -> parse_and_simplify -> parseJSON -> parse_con
  Execution halted
```

Using `Test Package` (Ctrl + Shift + T) works fine:
```r
==> Sourcing R files in 'tests' directory

Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
trying URL 'https://opendata.geoportal.gov.pl/ortofotomapa/41/41_3756_N-33-130-D-b-2-3.tif'
Content type 'application/octet-stream' length 2137288 bytes (2.0 MB)
==================================================
downloaded 2.0 MB

Tests complete
```

**Comment by yihui** [comment]
The testing framework should be irrelevant here (i.e., it doesn't matter which testing package you use---testit, testthat, tinytest, whatever...). It looks you were trying to parse JSON from a URL, and the URL returned HTML instead. The HTML code was incomplete in the error message, but I guess it may be "Request Rejected".

**Comment by kadyb** [comment]
Thanks for your response. You are right, I'm trying to parse JSON from a URL and the error come from this line:
`output = jsonlite::fromJSON(prepared_URL)`. However, except rcmdcheck test, everything works fine (the URL is valid, the server is running and returns a valid result).

This error is really weird because it never happened during normal use of the package or during `Test Package` procedure in RStudio. I can also use the testfile line by line without any error:

```r
library(sf)
library(testit)
library(rgugik)

polygon_path = system.file("datasets/search_area.gpkg", package = "rgugik")
polygon = read_sf(polygon_path)
req_df = DEM_request(polygon)

assert(
  "check if ouput is data frame",
  class(req_df) == "data.frame"
)

assert(
  "check number of rows",
  nrow(req_df) > 0
)

assert(
  "check number of columns",
  ncol(req_df) == 13
)
# everything works
```
Do you have any further recommendations?

**Comment by kadyb** [comment]
I rewrote the tests to **testthat** and the [same error](https://github.com/kadyb/rgugik/runs/1160076002?check_suite_focus=true) appears during `rcmdcheck` too.  So it is probably coming from **jsonlite**.

Log:
```r
> library(testthat)
> library(rgugik)
> 
> test_check("rgugik")
── 1. Error: (unknown) (@test-DEM_request.R#5)  ────────────────────────────────
lexical error: invalid char in json text.
                                       <html><head><title>Request Reje
                     (right here) ------^
Backtrace:
 1. rgugik::DEM_request(polygon)
 2. jsonlite::fromJSON(prepared_URL)
 3. jsonlite:::parse_and_simplify(...)
 4. jsonlite:::parseJSON(txt, bigint_as_char)
 5. jsonlite:::parse_con(txt, bigint_as_char)
```

**Comment by yihui** [comment]
In general, I don't recommend that you do testing against a remote URL, because this is definitely subject to failure for several possible reasons. You can't guarantee the URL is always accessible in any environment. If you must test it, you should consider downloading the resource (with `try()` or `tryCatch()`), and only do the test if the download was successful.
