### ISSUE TITLE
should the test files be placed under ./tests/testit or ./inst/tests/testit

### ISSUE THREAD

**Issue by shrektan** [yihui/testit#7]
I'm confused because clearly `test_pkg()`'s source code suggests `./inst/tests/testit` [but testit itself place the tests under `./tests/testit`](https://github.com/yihui/testit/tree/master/tests/testit). 

https://github.com/yihui/testit/blob/65768f8dbb45a1da8aab7369da38e1f3e3f5d0b8/R/testit.R#L172

So what's the correct way to do? 

Thanks.

**Comment by shrektan** [comment]
I see... it's because of the default param`dir = "testit"`. 

However, if I placed the tests file under `./tests/testit/test-xxx.R` then run `testit::test_pkg('pkgname')`, it would throw errors complaining test dir not found. 

I think it's because it should be run with the working directory being set to `./tests`. But it's kind of awkward because I have to switch back and off again and again.

I must understand something wrongly... (I think I may have figured it out when adding tests for xfun. Unfortunately, I can't recall it).

**Comment by yihui** [comment]
`./tests/testit` is the preferred place. The other place is also fine but not recommended (`R CMD INSTALL` will install tests, which are usually not useful to users).

To run tests, you can run `R CMD check`, or more easily, <kbd>Ctrl/Cmd + Shift + T</kbd> in RStudio, which will run all scripts under `.tests/`. For example: https://github.com/yihui/testit/blob/master/tests/test-all.R When running these scripts, the working directory will be switched to the `tests` directory.

**Comment by shrektan** [comment]
Yes, but R CMD check will do more than testing. Sometimes it’s time consuming. I prefer to just quickly run some tests as `devtools::test()` does. 

When `testit::test_pkg()` is used interactively, it should also try to find scripts under `./tests`. Does it sound good to you? If so I’m happy to file a PR.

**Comment by yihui** [comment]
Yes.

**Comment by yihui** [comment]
I have done it via a9f7bc15608c0d9ea8e59e364c3d0baa3e5c5757. Thanks!

**Comment by shrektan** [comment]
Great 👍
